spring:
  application:
    name: xyz-mcp-hub
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
  ai:
    mcp:
      server:
        name: utils
        version: 1.0.0
        protocol: STATELESS
        streamable-http:
          mcp-endpoint: /mcp/server/utils
vaadin:
  launch-browser: true
  url-mapping: /ui/*
